# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title approxFpop
#'
#' @description FPOP method (using the rectangle approximation of the sets) for  the multiple changepoint detection.
#' @param data is a matrix of data (p-rows x n-columns).
#' @param penalty is a value of penalty (a non-negative real number).
#' @param approximation is the type of approximation : 'rectangle' or 'sphere' (by default, 'rectangle').
#' @param intersection is the type of intersection : 'empty', 'all', 'last' or 'random' (by default, 'last').
#' @param exclusion is the type of intersection : 'empty', 'all'or 'random'(by default, 'all').
#' @param NbOfCands is the logical parameter (if NbOfCands = TRUE, than the file "NbOfCands.txt" contains the number of change candidates for each iteration.
#'
#' @return a list of  elements  = (changes, means, UnpenalizedCost, NumberOfCandidates).
#'
#' \describe{
#' \item{\code{changes}}{is the changepoint vector that gives the last index of each segment for the p-variate time series.}
#' \item{\code{means}}{is the list of successive means for the p-variate time series.}
#' \item{\code{UnpenalizedCost}}{is a number equal to the global cost.}
#' \item{\code{NumberOfCandidates}}{is a number of candidates at each iteration (vector).}
#' }
#'
#' @examples
#' N <- 100
#' Chpt <-50
#' Means <-  matrix(c(0,1,1,10), nrow = 2)
#' Noise <- 1
#' Dim <- 2
#' Penalty <- 6*log(100)
#' time_series <- rnormChanges(p = Dim, n = N, changes = Chpt, means = Means, noise = Noise)
#' time_series <- rnormChanges(p=3, n = 100, changes = NULL, means = matrix(0, ncol = 1, nrow = 3), noise = 1)
#' approxFpop(data = time_series, penalty = Penalty, approximation = 'rectangle', intersection = 'all', exclusion = 'all',  NbOfCands = TRUE)
#' approxFpop(data = time_series, penalty = Penalty, approximation = 'rectangle', intersection = 'all', exclusion = 'alllines',  NbOfCands = TRUE)
#' approxFpop(data = time_series, penalty = Penalty, approximation = 'rectangle', intersection = 'all', exclusion = 'allh',  NbOfCands = TRUE)
NULL

#'@title TestTwoApproxFpop
#'
#' @description Сomparing the parameters ("UnpenalizedCost", "LastChpt") for two different FPOP methods (using the rectangle approximation of the sets) .
#' @param data is a matrix of data (p-rows x n-columns).
#' @param penalty is a value of penalty (a non-negative real number).
#' @param approximation1 is the type of approximation : 'rectangle' or 'sphere' (by default, 'rectangle').
#' @param intersection1 is the type of intersection : 'empty', 'all', 'last', 'random' or 'sphere'(by default, 'last').
#' @param exclusion1 is the type of intersection : 'empty', 'all', 'random' or 'sphere'(by default, 'all').
#' @param str1 is the structure of a repository for exclusion disks : 'l' (all) or 'v'(reduction) (by default, 'v').
#' @param approximation2 is the type of approximation : 'rectangle' or 'sphere' (by default, 'rectangle').
#' @param intersection2 is the type of intersection : 'empty', 'all', 'last', 'random' or 'sphere'(by default, 'empty').
#' @param exclusion2 is the type of intersection : 'empty', 'all', 'random' or 'sphere'(by default, 'empty').
#' @param str2 is the structure of a repository for exclusion disks : 'l' (all) or 'v'(reduction) (by default, 'v').
#'
#' @return TRUE or FALSE
#'
#' \describe{
#' \item{\code{TRUE}}{ 'TRUE' if parameters are the same.}
#' \item{\code{FALSE}}{'TRUE' if parameters are different.}
#' }
#'
#' @examples
#' time_series <- rnormChanges(p = 2, n = N, changes = NULL, means = matrix(0, ncol = 1, nrow = 2), noise = 1)
NULL

approxFpop <- function(data, penalty, approximation = "rectangle", intersection = "all", exclusion = "all", NbOfCands = FALSE, NbOfEmpirCands = FALSE) {
    .Call(`_GeomFpop3D_approxFpop`, data, penalty, approximation, intersection, exclusion, NbOfCands, NbOfEmpirCands)
}

